"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Car_1 = require("./Car");
const ElectricCar_1 = require("./ElectricCar");
const mySedan = new Car_1.Sedan('Toyota', 'Camry', 2020, 'Blue');
console.log(mySedan.getCarInfo());
mySedan.startEngine();
mySedan.drive(50);
mySedan.stopEngine();
const myTesla = new ElectricCar_1.Tesla('Tesla', 'Model S', 2021, 100, 'red');
console.log(myTesla.getCarInfo());
myTesla.startEngine();
myTesla.drive(100);
myTesla.chargeBattery(50);
myTesla.stopEngine();
